version: '{branch}-{build}'
image:
- Visual Studio 2019
- Ubuntu2004
configuration:
- Debug
- Release
init:
- sh: sudo update-alternatives --set gcc /usr/bin/gcc-9
build_init:
- cmake -B build/ -DCMAKE_BUILD_TYPE=%CONFIGURATION% src/
build_script:
- cmake --build build/