version: '{branch}-{build}'
image:
- Visual Studio 2019
- Ubuntu2004
configuration:
- Debug
- Release
init:
- sh: sudo update-alternatives --set gcc /usr/bin/gcc-9
- sh: sudo update-alternatives --set clang /usr/bin/clang-10
before_build:
- cmake -B build/ -DCMAKE_BUILD_TYPE=%CONFIGURATION% src/
build_script:
- cmd: cmake --build build/
- ps: cmake --build build/