=============== ================== ====================
EVERYONE        USERS              CONTRIBUTORS
=============== ================== ====================
FAQ_            TUTORIALS_         `Coding style`_
Features_       `Anatomy of Vita`_ `Development cycle`_
Contributing_   API_               Miscellaneous_
Insights_
=============== ================== ====================

.. _FAQ: faq
.. _Features: features
.. _Contributing: https://github.com/morinim/vita/blob/master/CONTRIBUTING.md
.. _TUTORIALS: tutorials
.. _Anatomy of Vita: anatomy
.. _API: http://morinim.bitbucket.org/vita/api/
.. _Coding style: coding_style
.. _Development cycle: development_cycle
.. _Miscellaneous: miscellaneous
.. _Insights: insights_toc
